language: cpp

git:
  depth: 1

dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=clang-8
        - CXX=clang++-8

install:
  - . travis/install-cuda-xenial.sh

script:
  - mkdir build && cd build
  - cmake ../ -DCMAKE_CXX_FLAGS=-w -DENABLE_CUDA=ON -DSUPPRESS_CUDA_WARNINGS=TRUE -DBUILD_PROTEIN_CUDA_PLUGIN=ON
  - make install
