language: cpp

git:
  depth: 1

dist: xenial

matrix:
  include:
    - name: "gcc 7"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-7
        - CXX=g++-7
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"
    - name: "gcc 9 (Release)"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"
    - name: "gcc 9 (Debug)"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - BUILD_TYPE=Debug
        - GENERATOR="Unix Makefiles"
    - name: "gcc 9 (RelWithDebInfo)"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - BUILD_TYPE=RelWithDebInfo
        - GENERATOR="Unix Makefiles"
    - name: "gcc 9 (Ninja)"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=gcc-9
        - CXX=g++-9
        - BUILD_TYPE=Release
        - GENERATOR=Ninja
    - name: "clang 8"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - g++-9
            - libiomp-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - uuid-dev
            - libunwind8-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libcgal-qt5-dev
            - libcgal-dev
      env:
        - CC=clang-8
        - CXX=clang++-8
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"

install:
  - . travis/install-cuda-xenial.sh

script:
  - mkdir build && cd build
  - cmake .. -G"$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-w -DENABLE_CUDA=ON -DSUPPRESS_CUDA_WARNINGS=TRUE -DBUILD_ADIOS_PLUGIN_PLUGIN=ON -DBUILD_PROTEIN_CUDA_PLUGIN=ON -DBUILD_IMAGEVIEWER2_PLUGIN=ON -DBUILD_MEGAMOL101_PLUGIN=ON -DBUILD_MOLECULARMAPS_PLUGIN=ON -DBUILD_REMOTE_PLUGIN=ON
  - cmake --build .. --target install --config $BUILD_TYPE
