language: generic

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y uuid-dev
  - sudo apt-get install -y libunwind8-dev
  - sudo apt-get install -y libxrandr-dev
  - sudo apt-get install -y libxinerama-dev
  - sudo apt-get install -y libxcursor-dev
  - sudo apt-get install -y libxi-dev

script:
  - ci/build.sh
  